default: &default
  adapter: postgresql
  encoding: unicode
  template: template0
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: falsocket_development

test:
  <<: *default
  database: falsocket_test

production:
  <<: *default
  database: falsocket_production
  username: falsocket
  password: <%= ENV["FALSOCKET_DATABASE_PASSWORD"] %>

